CREATE TABLE products (
 id integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
      name VARCHAR(40) NOT NULL,
      descx VARCHAR(500) NOT NULL,
      price VARCHAR(40) NOT NULL,
      img VARCHAR(40) NOT NULL


);
INSERT INTO products
(name, descx, price, img )
VALUES
('Goku','bla' , 600, '/goku.gif' ),
('Garou','dsfd' , 500, '/garou.gif' ),
('DemonSlayer','slayer' , 100, '/demonSlayer.gif' ),
('Sukuna', 'sakuna', 200, '/sukuna.gif'),
('hero', 'heronhreo', 600, '/hero.gif'),
('YourName', 'cry' , 700, '/yourname.gif');